services:
  n8n:
    image: 'docker.n8n.io/n8nio/n8n:1.111.1'
    environment:
      - SERVICE_FQDN_N8N_5678
      - 'N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}'
      - 'WEBHOOK_URL=${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - 'GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Berlin}'
      - 'TZ=${TZ:-Europe/Berlin}'
    volumes:
      - 'n8n-data:/home/node/.n8n'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - coolify
    ports:
      - '5678:5678'
  ffmpeg-api:
    image: 'kazhar/ffmpeg-api:latest'
    environment:
      - FILE_SIZE_LIMIT_BYTES=524288000
    networks:
      - coolify
    ports:
      - '3000:3000'
    restart: unless-stopped
networks:
  coolify:
    external: true
